INSERT INTO departments (prefix, name) VALUES
('ACCT', 'Accounting'),
('ACC', 'Accounting - CPS'),
('AVM', 'Advanced Manufacturing Systems - CPS'),
('AFCS', 'Africana Studies'),
('AFRS', 'African Studies'),
('AMSL', 'American Sign Language'),
('ALY', 'Analytics - CPS'),
('ANTH', 'Anthropology'),
('ANT', 'Anthropology - CPS'),
('APL', 'Applied Logistics - CPS'),
('ARAB', 'Arabic'),
('ARCH', 'Architecture'),
('ARMY', 'Army ROTC'),
('ART', 'Art - CPS'),
('ARTG', 'Art - Design'),
('ARTF', 'Art - Fundamentals'),
('ARTE', 'Art - General'),
('ARTH', 'Art - History'),
('ARTD', 'Art - Media Arts'),
('AACE', 'Arts Administration and Cultural Entrepreneurship'),
('ARTS', 'Art - Studio'),
('ASNS', 'Asian Studies'),
('BNSC', 'Behavioral Neuroscience'),
('BIOC', 'Biochemistry'),
('BIOE', 'Bioengineering'),
('BINF', 'Bioinformatics'),
('BIOL', 'Biology'),
('BIO', 'Biology - CPS'),
('BIOT', 'Biotechnology'),
('BTC', 'Biotechnology - CPS'),
('BUSN', 'Business Administration'),
('EXSC', 'Cardiopulmonary and Exercise Science'),
('CHME', 'Chemical Engineering'),
('CHEM', 'Chemistry and Chemical Biology'),
('CHM', 'Chemistry - CPS'),
('CHNS', 'Chinese'),
('CIVE', 'Civil and Environmental Engineering'),
('CED', 'Commerce and Economic Development - CPS'),
('COMM', 'Communication Studies'),
('CMN', 'Communication Studies - CPS'),
('CMMN', 'Communication Studies - CPS Specialty'),
('CET', 'Computer Engineering Technology - CPS'),
('CS', 'Computer Science'),
('CSYE', 'Computer Systems Engineering'),
('CMG', 'Construction Management - CPS'),
('COOP', 'Cooperative Education'),
('COP', 'Cooperative Education - CPS'),
('EXED', 'Cooperative/Experiential Education'),
('EEAM', 'Co-op/Experiential Education in Arts, Media, and Design'),
('EEBA', 'Co-op/Experiential Education in Business'),
('EESC', 'Co-op/Experiential Education in Science'),
('EESH', 'Co-op/Experiential Education in Social Sciences and Humanities'),
('INNO', 'Corporate Innovation'),
('CAEP', 'Counseling and Applied Educational Psychology'),
('CRTE', 'Creative Technologies'),
('CJS', 'Criminal Justice - CPS'),
('CRIM', 'Criminal Justice'),
('CLTR', 'Culture'),
('CY', 'Cybersecurity'),
('DA', 'Data Analytics'),
('DAMG', 'Data Architecture Management'),
('DS', 'Data Science'),
('DEAF', 'Deaf Studies'),
('DGM', 'Digital Media - CPS'),
('DGTR', 'Digital Transformation'),
('ENVR', 'Earth and Environmental Sciences'),
('EEMB', 'Ecology, Evolution, and Marine Biology'),
('ECN', 'Economics - CPS'),
('ECNM', 'Economics - CPS Specialty'),
('ECON', 'Economics'),
('EDUT', 'Education - California Prepared'),
('EDU', 'Education - CPS'),
('EDUC', 'Education'),
('EECE', 'Electrical and Computer Engineering'),
('EET', 'Electrical Engineering Technology - CPS'),
('ENSY', 'Energy Systems'),
('ENCP', 'Engineering Cooperative Education'),
('ENGR', 'Engineering Interdisciplinary'),
('ENLR', 'Engineering Leadership'),
('EMGT', 'Engineering Management'),
('ENG', 'English - CPS'),
('ENGL', 'English'),
('ENGW', 'English Writing'),
('EAI', 'Enterprise Artificial Intelligence'),
('ENTR', 'Entrepreneurship and Innovation'),
('ESC', 'Environmental Science - CPS'),
('ENVS', 'Environmental Studies'),
('EXRE', 'Extended Realities'),
('FINA', 'Finance and Insurance'),
('FIN', 'Finance - CPS'),
('FSEM', 'First-Year Seminar'),
('FRNH', 'French'),
('GAME', 'Game Design'),
('GSND', 'Game Science and Design'),
('GE', 'General Engineering'),
('GET', 'General Engineering Technology - CPS'),
('GENS', 'General Studies'),
('GIS', 'Geographic Information Systems - CPS'),
('GRMN', 'German'),
('GST', 'Global Studies - CPS'),
('GBST', 'Global Studies'),
('HINF', 'Health Informatics'),
('HMG', 'Health Management - CPS'),
('HSC', 'Health Science - CPS'),
('HSCI', 'Health Science'),
('HLTH', 'Health Science - Interdisciplinary'),
('HBRW', 'Hebrew'),
('HST', 'History - CPS'),
('HIST', 'History'),
('HLS', 'Homeland Security - CPS'),
('HONR', 'Honors Program'),
('HRM', 'Human Resources Management - CPS'),
('HRMG', 'Human Resources Management'),
('HSV', 'Human Services - CPS'),
('HUSV', 'Human Services'),
('IE', 'Industrial Engineering'),
('IS', 'Information Science'),
('INFO', 'Information Systems Program'),
('ITC', 'Information Technology - CPS'),
('INS', 'Insurance - CPS'),
('INT', 'Interdisciplinary Studies - CPS'),
('INAM', 'Interdisciplinary Studies in Arts, Media, and Design'),
('INSC', 'Interdisciplinary Studies in Science'),
('INSH', 'Interdisciplinary Studies in Social Sciences and Humanities'),
('INMI', 'Interdisciplinary Studies - Mills College at Northeastern'),
('INPR', 'Interdisciplinary Studies - Office of the Provost'),
('INTL', 'International Affairs'),
('INTB', 'International Business'),
('INTP', 'Interpreting'),
('ITLN', 'Italian'),
('JPNS', 'Japanese'),
('JWSS', 'Jewish Studies'),
('JRNL', 'Journalism'),
('KORE', 'Korean'),
('LARC', 'Landscape Architecture'),
('LANG', 'Language - General'),
('LACS', 'Latin American and Caribbean Studies'),
('LWP', 'Law and Policy - CPS'),
('LPSC', 'Law and Public Policy'),
('LW', 'Law (for Non-Law School Students)'),
('LAW', 'Law'),
('LDR', 'Leadership Studies - CPS'),
('LS', 'Legal Studies'),
('LST', 'Liberal Studies - CPS'),
('LING', 'Linguistics'),
('MGT', 'Management - CPS'),
('MISM', 'Management Information Systems'),
('MGMT', 'Management'),
('MGSC', 'Management Science'),
('MECN', 'Managerial Economics'),
('MKT', 'Marketing - CPS'),
('MKTG', 'Marketing'),
('MATL', 'Materials Engineering'),
('MTH', 'Mathematics - CPS'),
('MATM', 'Mathematics - CPS Specialty'),
('MATH', 'Mathematics'),
('MEIE', 'Mechanical and Industrial Engineering'),
('ME', 'Mechanical Engineering'),
('MET', 'Mechanical Engineering Technology - CPS'),
('MSCR', 'Media and Screen Studies'),
('MSCI', 'Medical Sciences'),
('MUS', 'Music - CPS'),
('MUSI', 'Music Industry'),
('MUSC', 'Music'),
('MUST', 'Music Technology'),
('NNMD', 'Nanomedicine'),
('NETS', 'Network Science'),
('NPM', 'Nonprofit Management - CPS'),
('NRSG', 'Nursing'),
('NTR', 'Nutrition - CPS'),
('OR', 'Operations Research'),
('ORGB', 'Organizational Behavior'),
('PHSC', 'Pharmaceutical Science'),
('PMST', 'Pharmaceutics'),
('PMCL', 'Pharmacology'),
('PHMD', 'Pharmacy Practice'),
('PHDL', 'PhD Experiential Leadership'),
('PHL', 'Philosophy - CPS'),
('PHLS', 'Philosophy - CPS Specialty'),
('PHIL', 'Philosophy'),
('PTH', 'Physical Therapy - CPS'),
('PT', 'Physical Therapy'),
('PA', 'Physician Assistant'),
('PHY', 'Physics - CPS'),
('PHYS', 'Physics'),
('POL', 'Political Science - CPS'),
('PLSC', 'Political Science - CPS Specialty'),
('POLS', 'Political Science'),
('PORT', 'Portuguese'),
('PJM', 'Project Management - CPS'),
('PSY', 'Psychology - CPS'),
('PSYC', 'Psychology'),
('PHTH', 'Public Health'),
('PPUA', 'Public Policy and Urban Affairs'),
('PBR', 'Public Relations - CPS'),
('PREL', 'Public Relations'),
('RGA', 'Regulatory Affairs - CPS'),
('RFA', 'Regulatory Affairs of Food - CPS'),
('RMS', 'Remote Sensing - CPS'),
('RPT', 'Respiratory Therapy - CPS'),
('RSSN', 'Russian'),
('SMT', 'Sales Management - CPS'),
('SOC', 'Sociology - CPS'),
('SCLY', 'Sociology - CPS Specialty'),
('SOCL', 'Sociology'),
('SPNS', 'Spanish'),
('SLPA', 'Speech-Language Pathology and Audiology'),
('SIA', 'Strategic Intelligence and Analysis - CPS'),
('STRT', 'Strategy'),
('ABRC', 'Study Abroad - CPS Specialty'),
('ABRL', 'Study Abroad - Law'),
('SCHM', 'Supply Chain Management'),
('SBSY', 'Sustainable Building Systems'),
('SUEN', 'Sustainable Urban Environments'),
('TCC', 'Technical Communications - CPS'),
('TELR', 'Technology Leadership'),
('TELE', 'Telecommunication Systems'),
('THTR', 'Theatre'),
('WMNS', 'Women’s, Gender, and Sexuality Studies');
